// flow-typed signature: 69fb720a9030102db108a01b89d3a3b7
// flow-typed version: <<STUB>>/badgs_v^1.1.1/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'badgs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'badgs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'badgs/bin/cli' {
  declare module.exports: any;
}

declare module 'badgs/lib/index' {
  declare module.exports: any;
}

declare module 'badgs/lib/middleware' {
  declare module.exports: any;
}

declare module 'badgs/lib/templates/flat-square' {
  declare module.exports: any;
}

declare module 'badgs/lib/templates/flat' {
  declare module.exports: any;
}

declare module 'badgs/lib/templates/plastic' {
  declare module.exports: any;
}

declare module 'badgs/src/bin/cli' {
  declare module.exports: any;
}

declare module 'badgs/src/lib/index' {
  declare module.exports: any;
}

declare module 'badgs/src/lib/middleware' {
  declare module.exports: any;
}

declare module 'badgs/src/lib/templates/flat-square' {
  declare module.exports: any;
}

declare module 'badgs/src/lib/templates/flat' {
  declare module.exports: any;
}

declare module 'badgs/src/lib/templates/plastic' {
  declare module.exports: any;
}

declare module 'badgs/test/badgs.test' {
  declare module.exports: any;
}

declare module 'badgs/test/connect' {
  declare module.exports: any;
}

declare module 'badgs/test/express' {
  declare module.exports: any;
}

declare module 'badgs/test/generate' {
  declare module.exports: any;
}

declare module 'badgs/test/middleware.test' {
  declare module.exports: any;
}

declare module 'badgs/test/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'badgs/bin/cli.js' {
  declare module.exports: $Exports<'badgs/bin/cli'>;
}
declare module 'badgs/lib/index.js' {
  declare module.exports: $Exports<'badgs/lib/index'>;
}
declare module 'badgs/lib/middleware.js' {
  declare module.exports: $Exports<'badgs/lib/middleware'>;
}
declare module 'badgs/lib/templates/flat-square.js' {
  declare module.exports: $Exports<'badgs/lib/templates/flat-square'>;
}
declare module 'badgs/lib/templates/flat.js' {
  declare module.exports: $Exports<'badgs/lib/templates/flat'>;
}
declare module 'badgs/lib/templates/plastic.js' {
  declare module.exports: $Exports<'badgs/lib/templates/plastic'>;
}
declare module 'badgs/src/bin/cli.js' {
  declare module.exports: $Exports<'badgs/src/bin/cli'>;
}
declare module 'badgs/src/lib/index.js' {
  declare module.exports: $Exports<'badgs/src/lib/index'>;
}
declare module 'badgs/src/lib/middleware.js' {
  declare module.exports: $Exports<'badgs/src/lib/middleware'>;
}
declare module 'badgs/src/lib/templates/flat-square.js' {
  declare module.exports: $Exports<'badgs/src/lib/templates/flat-square'>;
}
declare module 'badgs/src/lib/templates/flat.js' {
  declare module.exports: $Exports<'badgs/src/lib/templates/flat'>;
}
declare module 'badgs/src/lib/templates/plastic.js' {
  declare module.exports: $Exports<'badgs/src/lib/templates/plastic'>;
}
declare module 'badgs/test/badgs.test.js' {
  declare module.exports: $Exports<'badgs/test/badgs.test'>;
}
declare module 'badgs/test/connect.js' {
  declare module.exports: $Exports<'badgs/test/connect'>;
}
declare module 'badgs/test/express.js' {
  declare module.exports: $Exports<'badgs/test/express'>;
}
declare module 'badgs/test/generate.js' {
  declare module.exports: $Exports<'badgs/test/generate'>;
}
declare module 'badgs/test/middleware.test.js' {
  declare module.exports: $Exports<'badgs/test/middleware.test'>;
}
declare module 'badgs/test/setup.js' {
  declare module.exports: $Exports<'badgs/test/setup'>;
}
