// flow-typed signature: 2fc05c9503da4bf1db0a05fd737cbf94
// flow-typed version: <<STUB>>/git-pre-commit_v^2.1.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'git-pre-commit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'git-pre-commit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'git-pre-commit/gulp/args' {
  declare module.exports: any;
}

declare module 'git-pre-commit/gulp/config' {
  declare module.exports: any;
}

declare module 'git-pre-commit/gulp/tasks/hooks' {
  declare module.exports: any;
}

declare module 'git-pre-commit/gulp/tasks/lint-js' {
  declare module.exports: any;
}

declare module 'git-pre-commit/gulp/tasks/tests' {
  declare module.exports: any;
}

declare module 'git-pre-commit/Gulpfile' {
  declare module.exports: any;
}

declare module 'git-pre-commit/pre-commit-utils/git-manager' {
  declare module.exports: any;
}

declare module 'git-pre-commit/pre-commit-utils/gulp-utils' {
  declare module.exports: any;
}

declare module 'git-pre-commit/pre-commit-utils/package-manager-utils' {
  declare module.exports: any;
}

declare module 'git-pre-commit/pre-commit-utils/path-utils' {
  declare module.exports: any;
}

declare module 'git-pre-commit/scripts/pre-commit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'git-pre-commit/gulp/args.js' {
  declare module.exports: $Exports<'git-pre-commit/gulp/args'>;
}
declare module 'git-pre-commit/gulp/config.js' {
  declare module.exports: $Exports<'git-pre-commit/gulp/config'>;
}
declare module 'git-pre-commit/gulp/tasks/hooks.js' {
  declare module.exports: $Exports<'git-pre-commit/gulp/tasks/hooks'>;
}
declare module 'git-pre-commit/gulp/tasks/lint-js.js' {
  declare module.exports: $Exports<'git-pre-commit/gulp/tasks/lint-js'>;
}
declare module 'git-pre-commit/gulp/tasks/tests.js' {
  declare module.exports: $Exports<'git-pre-commit/gulp/tasks/tests'>;
}
declare module 'git-pre-commit/Gulpfile.js' {
  declare module.exports: $Exports<'git-pre-commit/Gulpfile'>;
}
declare module 'git-pre-commit/pre-commit-utils/git-manager.js' {
  declare module.exports: $Exports<'git-pre-commit/pre-commit-utils/git-manager'>;
}
declare module 'git-pre-commit/pre-commit-utils/gulp-utils.js' {
  declare module.exports: $Exports<'git-pre-commit/pre-commit-utils/gulp-utils'>;
}
declare module 'git-pre-commit/pre-commit-utils/package-manager-utils.js' {
  declare module.exports: $Exports<'git-pre-commit/pre-commit-utils/package-manager-utils'>;
}
declare module 'git-pre-commit/pre-commit-utils/path-utils.js' {
  declare module.exports: $Exports<'git-pre-commit/pre-commit-utils/path-utils'>;
}
declare module 'git-pre-commit/scripts/pre-commit.js' {
  declare module.exports: $Exports<'git-pre-commit/scripts/pre-commit'>;
}
