// flow-typed signature: c56c0ad829b98b70ad89abb06bff06ac
// flow-typed version: <<STUB>>/got_v^6.3.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'got'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'got' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'got/index' {
  declare module.exports: $Exports<'got'>;
}
declare module 'got/index.js' {
  declare module.exports: $Exports<'got'>;
}
