// flow-typed signature: 8c6006923bd94afe4ad8da62ecf2677d
// flow-typed version: <<STUB>>/intel_v^1.1.1/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'intel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'intel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'intel/lib/config' {
  declare module.exports: any;
}

declare module 'intel/lib/console' {
  declare module.exports: any;
}

declare module 'intel/lib/filter' {
  declare module.exports: any;
}

declare module 'intel/lib/filterer' {
  declare module.exports: any;
}

declare module 'intel/lib/formatter' {
  declare module.exports: any;
}

declare module 'intel/lib/handlers/console' {
  declare module.exports: any;
}

declare module 'intel/lib/handlers/file' {
  declare module.exports: any;
}

declare module 'intel/lib/handlers/handler' {
  declare module.exports: any;
}

declare module 'intel/lib/handlers/index' {
  declare module.exports: any;
}

declare module 'intel/lib/handlers/null' {
  declare module.exports: any;
}

declare module 'intel/lib/handlers/stream' {
  declare module.exports: any;
}

declare module 'intel/lib/index' {
  declare module.exports: any;
}

declare module 'intel/lib/levels' {
  declare module.exports: any;
}

declare module 'intel/lib/logger' {
  declare module.exports: any;
}

declare module 'intel/lib/record' {
  declare module.exports: any;
}

declare module 'intel/lib/utils/fn' {
  declare module.exports: any;
}

declare module 'intel/lib/utils/json' {
  declare module.exports: any;
}

declare module 'intel/lib/utils/klass' {
  declare module.exports: any;
}

declare module 'intel/lib/utils/printf' {
  declare module.exports: any;
}

// Filename aliases
declare module 'intel/lib/config.js' {
  declare module.exports: $Exports<'intel/lib/config'>;
}
declare module 'intel/lib/console.js' {
  declare module.exports: $Exports<'intel/lib/console'>;
}
declare module 'intel/lib/filter.js' {
  declare module.exports: $Exports<'intel/lib/filter'>;
}
declare module 'intel/lib/filterer.js' {
  declare module.exports: $Exports<'intel/lib/filterer'>;
}
declare module 'intel/lib/formatter.js' {
  declare module.exports: $Exports<'intel/lib/formatter'>;
}
declare module 'intel/lib/handlers/console.js' {
  declare module.exports: $Exports<'intel/lib/handlers/console'>;
}
declare module 'intel/lib/handlers/file.js' {
  declare module.exports: $Exports<'intel/lib/handlers/file'>;
}
declare module 'intel/lib/handlers/handler.js' {
  declare module.exports: $Exports<'intel/lib/handlers/handler'>;
}
declare module 'intel/lib/handlers/index.js' {
  declare module.exports: $Exports<'intel/lib/handlers/index'>;
}
declare module 'intel/lib/handlers/null.js' {
  declare module.exports: $Exports<'intel/lib/handlers/null'>;
}
declare module 'intel/lib/handlers/stream.js' {
  declare module.exports: $Exports<'intel/lib/handlers/stream'>;
}
declare module 'intel/lib/index.js' {
  declare module.exports: $Exports<'intel/lib/index'>;
}
declare module 'intel/lib/levels.js' {
  declare module.exports: $Exports<'intel/lib/levels'>;
}
declare module 'intel/lib/logger.js' {
  declare module.exports: $Exports<'intel/lib/logger'>;
}
declare module 'intel/lib/record.js' {
  declare module.exports: $Exports<'intel/lib/record'>;
}
declare module 'intel/lib/utils/fn.js' {
  declare module.exports: $Exports<'intel/lib/utils/fn'>;
}
declare module 'intel/lib/utils/json.js' {
  declare module.exports: $Exports<'intel/lib/utils/json'>;
}
declare module 'intel/lib/utils/klass.js' {
  declare module.exports: $Exports<'intel/lib/utils/klass'>;
}
declare module 'intel/lib/utils/printf.js' {
  declare module.exports: $Exports<'intel/lib/utils/printf'>;
}
