// flow-typed signature: a4af9154dceaecc3e6628061913d50a9
// flow-typed version: <<STUB>>/nodemailer_v^2.7.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nodemailer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'nodemailer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nodemailer/lib/http-proxy' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/nodemailer' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/template-sender' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nodemailer/lib/http-proxy.js' {
  declare module.exports: $Exports<'nodemailer/lib/http-proxy'>;
}
declare module 'nodemailer/lib/nodemailer.js' {
  declare module.exports: $Exports<'nodemailer/lib/nodemailer'>;
}
declare module 'nodemailer/lib/template-sender.js' {
  declare module.exports: $Exports<'nodemailer/lib/template-sender'>;
}
