// flow-typed signature: 5d1afd4f4d3604dc9bcc824e14bd6107
// flow-typed version: <<STUB>>/nodemailer-sendmail-transport_v^1.0.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nodemailer-sendmail-transport'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'nodemailer-sendmail-transport' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nodemailer-sendmail-transport/Gruntfile' {
  declare module.exports: any;
}

declare module 'nodemailer-sendmail-transport/src/sendmail-transport' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nodemailer-sendmail-transport/Gruntfile.js' {
  declare module.exports: $Exports<'nodemailer-sendmail-transport/Gruntfile'>;
}
declare module 'nodemailer-sendmail-transport/src/sendmail-transport.js' {
  declare module.exports: $Exports<'nodemailer-sendmail-transport/src/sendmail-transport'>;
}
