// flow-typed signature: 97831520b08c31959e72a35a743f93ea
// flow-typed version: <<STUB>>/node-xmpp-client_v^3.0.2/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-xmpp-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-xmpp-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-xmpp-client/browserify' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/examples/anonymous' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/examples/answer_bot' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/examples/browser/chat' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/examples/echo_bot_oauth' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/examples/echo_bot' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/examples/in-band-registeration' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/examples/prebind' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/examples/question_bot' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/examples/send_message' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/lib/authentication/anonymous' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/lib/authentication/digestmd5' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/lib/authentication/external' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/lib/authentication/mechanism' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/lib/authentication/plain' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/lib/authentication/xoauth2' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/lib/bosh' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/lib/Client' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/lib/prebind' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/lib/sasl' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/lib/session' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/lib/websockets' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/test/authentication/anonymous' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/test/authentication/digestmd5' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/test/authentication/external' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/test/authentication/plain' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/test/authentication/xoauth2' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/test/reconnect' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/test/sasl' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/test/stream' {
  declare module.exports: any;
}

declare module 'node-xmpp-client/test/websocket' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-xmpp-client/browserify.js' {
  declare module.exports: $Exports<'node-xmpp-client/browserify'>;
}
declare module 'node-xmpp-client/examples/anonymous.js' {
  declare module.exports: $Exports<'node-xmpp-client/examples/anonymous'>;
}
declare module 'node-xmpp-client/examples/answer_bot.js' {
  declare module.exports: $Exports<'node-xmpp-client/examples/answer_bot'>;
}
declare module 'node-xmpp-client/examples/browser/chat.js' {
  declare module.exports: $Exports<'node-xmpp-client/examples/browser/chat'>;
}
declare module 'node-xmpp-client/examples/echo_bot_oauth.js' {
  declare module.exports: $Exports<'node-xmpp-client/examples/echo_bot_oauth'>;
}
declare module 'node-xmpp-client/examples/echo_bot.js' {
  declare module.exports: $Exports<'node-xmpp-client/examples/echo_bot'>;
}
declare module 'node-xmpp-client/examples/in-band-registeration.js' {
  declare module.exports: $Exports<'node-xmpp-client/examples/in-band-registeration'>;
}
declare module 'node-xmpp-client/examples/prebind.js' {
  declare module.exports: $Exports<'node-xmpp-client/examples/prebind'>;
}
declare module 'node-xmpp-client/examples/question_bot.js' {
  declare module.exports: $Exports<'node-xmpp-client/examples/question_bot'>;
}
declare module 'node-xmpp-client/examples/send_message.js' {
  declare module.exports: $Exports<'node-xmpp-client/examples/send_message'>;
}
declare module 'node-xmpp-client/index' {
  declare module.exports: $Exports<'node-xmpp-client'>;
}
declare module 'node-xmpp-client/index.js' {
  declare module.exports: $Exports<'node-xmpp-client'>;
}
declare module 'node-xmpp-client/lib/authentication/anonymous.js' {
  declare module.exports: $Exports<'node-xmpp-client/lib/authentication/anonymous'>;
}
declare module 'node-xmpp-client/lib/authentication/digestmd5.js' {
  declare module.exports: $Exports<'node-xmpp-client/lib/authentication/digestmd5'>;
}
declare module 'node-xmpp-client/lib/authentication/external.js' {
  declare module.exports: $Exports<'node-xmpp-client/lib/authentication/external'>;
}
declare module 'node-xmpp-client/lib/authentication/mechanism.js' {
  declare module.exports: $Exports<'node-xmpp-client/lib/authentication/mechanism'>;
}
declare module 'node-xmpp-client/lib/authentication/plain.js' {
  declare module.exports: $Exports<'node-xmpp-client/lib/authentication/plain'>;
}
declare module 'node-xmpp-client/lib/authentication/xoauth2.js' {
  declare module.exports: $Exports<'node-xmpp-client/lib/authentication/xoauth2'>;
}
declare module 'node-xmpp-client/lib/bosh.js' {
  declare module.exports: $Exports<'node-xmpp-client/lib/bosh'>;
}
declare module 'node-xmpp-client/lib/Client.js' {
  declare module.exports: $Exports<'node-xmpp-client/lib/Client'>;
}
declare module 'node-xmpp-client/lib/prebind.js' {
  declare module.exports: $Exports<'node-xmpp-client/lib/prebind'>;
}
declare module 'node-xmpp-client/lib/sasl.js' {
  declare module.exports: $Exports<'node-xmpp-client/lib/sasl'>;
}
declare module 'node-xmpp-client/lib/session.js' {
  declare module.exports: $Exports<'node-xmpp-client/lib/session'>;
}
declare module 'node-xmpp-client/lib/websockets.js' {
  declare module.exports: $Exports<'node-xmpp-client/lib/websockets'>;
}
declare module 'node-xmpp-client/test/authentication/anonymous.js' {
  declare module.exports: $Exports<'node-xmpp-client/test/authentication/anonymous'>;
}
declare module 'node-xmpp-client/test/authentication/digestmd5.js' {
  declare module.exports: $Exports<'node-xmpp-client/test/authentication/digestmd5'>;
}
declare module 'node-xmpp-client/test/authentication/external.js' {
  declare module.exports: $Exports<'node-xmpp-client/test/authentication/external'>;
}
declare module 'node-xmpp-client/test/authentication/plain.js' {
  declare module.exports: $Exports<'node-xmpp-client/test/authentication/plain'>;
}
declare module 'node-xmpp-client/test/authentication/xoauth2.js' {
  declare module.exports: $Exports<'node-xmpp-client/test/authentication/xoauth2'>;
}
declare module 'node-xmpp-client/test/reconnect.js' {
  declare module.exports: $Exports<'node-xmpp-client/test/reconnect'>;
}
declare module 'node-xmpp-client/test/sasl.js' {
  declare module.exports: $Exports<'node-xmpp-client/test/sasl'>;
}
declare module 'node-xmpp-client/test/stream.js' {
  declare module.exports: $Exports<'node-xmpp-client/test/stream'>;
}
declare module 'node-xmpp-client/test/websocket.js' {
  declare module.exports: $Exports<'node-xmpp-client/test/websocket'>;
}
