// flow-typed signature: bd9b9a73083ff4bcb32c24d93ea4f0ad
// flow-typed version: <<STUB>>/node-architect_v^0.0.15/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-architect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-architect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-architect/lib/architect' {
  declare module.exports: any;
}

declare module 'node-architect/tests/index' {
  declare module.exports: any;
}

declare module 'node-architect/tests/mocks/es6' {
  declare module.exports: any;
}

declare module 'node-architect/tests/mocks/test' {
  declare module.exports: any;
}

declare module 'node-architect/tests/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-architect/lib/architect.js' {
  declare module.exports: $Exports<'node-architect/lib/architect'>;
}
declare module 'node-architect/tests/index.js' {
  declare module.exports: $Exports<'node-architect/tests/index'>;
}
declare module 'node-architect/tests/mocks/es6.js' {
  declare module.exports: $Exports<'node-architect/tests/mocks/es6'>;
}
declare module 'node-architect/tests/mocks/test.js' {
  declare module.exports: $Exports<'node-architect/tests/mocks/test'>;
}
declare module 'node-architect/tests/setup.js' {
  declare module.exports: $Exports<'node-architect/tests/setup'>;
}
