// flow-typed signature: 465a73ed5b5a5d8b828a91c213369557
// flow-typed version: <<STUB>>/response-time_v^2.3.1/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'response-time'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'response-time' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'response-time/index' {
  declare module.exports: $Exports<'response-time'>;
}
declare module 'response-time/index.js' {
  declare module.exports: $Exports<'response-time'>;
}
